import base64
from datetime import UTC, datetime
from io import BytesIO

from fastapi.testclient import TestClient
from PIL import Image

from app.main import app

client = TestClient(app)


def create_test_image() -> str:
    image = Image.new("RGB", (128, 128), "white")
    buffer = BytesIO()
    image.save(buffer, format="JPEG")

    return base64.b64encode(buffer.getvalue()).decode("ascii")


def test_submit_frame():
    payload = {
        "robot_id": "aido_001",
        "platform": "aido",
        "timestamp": datetime.now(UTC).isoformat(),
        "image_base64": create_test_image(),
    }

    response = client.post("/v1/frames", json=payload)

    assert response.status_code == 202

    result = response.json()

    assert result["status"] == "accepted"
    assert result["robot_id"] == "aido_001"
    assert "frame_id" in result
    assert "job_id" in result

    # Retrieve the metadata generated by the backend.
    frame_response = client.get(f"/v1/frames/{result['frame_id']}")

    assert frame_response.status_code == 200

    metadata = frame_response.json()["frame"]

    assert metadata["width"] == 128
    assert metadata["height"] == 128
    assert metadata["format"] == "jpeg"
    assert len(metadata["checksum"]) == 64


def test_frame_not_found():
    response = client.get("/v1/frames/nonexistent-frame")

    assert response.status_code == 404

    error = response.json()

    assert error["code"] == "FRAME_NOT_FOUND"
    assert "request_id" in error
    assert "message" in error
    assert "details" in error


def test_invalid_image():
    response = client.post(
        "/v1/frames",
        json={
            "robot_id": "aido_001",
            "platform": "aido",
            "timestamp": datetime.now(UTC).isoformat(),
            "image_base64": "not-valid-base64",
        },
    )

    assert response.status_code == 422
    assert response.json()["code"] == "INVALID_IMAGE"


def test_missing_required_field():
    response = client.post(
        "/v1/frames",
        json={
            "platform": "aido",
            "timestamp": datetime.now(UTC).isoformat(),
            "image_base64": create_test_image(),
        },
    )

    assert response.status_code == 422
    assert response.json()["code"] == "VALIDATION_ERROR"


# Now test the case the frame is non existent
def test_missing_frame():
    response = client.get("/v1/frames/nonexistent")
    assert response.status_code == 404


def test_robot_state():
    response = client.get("/v1/robots/aido_001/state")

    assert response.status_code == 200
    assert response.json()["state"] == "unknown"
    assert response.json()["source"] == "stub"


def test_detections():
    response = client.get("/v1/detections?robot_id=aido_001&limit=10")

    assert response.status_code == 200
    assert response.json()["items"] == []


# Test if an invalid frame is passed in
def test_invalid_frame():
    response = client.post(
        "/v1/frames",
        json={
            "robot_id": "aido_001",
            "timestamp": "not-a-date",
            "image_base64": "bad-data",
        },
    )

    assert response.status_code == 422


def test_empty_frame():
    response = client.post("/v1/frames", json={"image_base64": ""})

    assert response.status_code == 422
